"""add authentication fields to users

Revision ID: 48f9c4b677ca
Revises: 4e7372560752
Create Date: 2026-09-21 18:46:43.835634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f9c4b677ca'
down_revision: Union[str, Sequence[str], None] = '4e7372560752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.execute(
        "UPDATE users SET hashed_password = "
        "'$2b$12$C6UzMDM.H6dfI/f/IKcEe.6O5YlN2d6J2XJw0q5Q6V7Y8Z9A0B1C2' "
        "WHERE hashed_password IS NULL"
    )
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
